"""Output — generate the living architecture document.

Supports incremental append and reverse-chronological ordering.
"""
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path


def render_markdown(
    entries: list[dict],
    output_path: str = "living-arch.md",
    since: str | None = None,
) -> str:
    """Generate the living architecture markdown doc.

    Args:
        entries: List of narrated change entries, each with:
            - timestamp: ISO timestamp
            - summary: str
            - rationale: str
            - data_flow: str
            - impact: list[str]
            - diagram: str (mermaid)
            - changes: list[dict] (structural changes)
            - task: str (optional)
            - diagram_path: str (optional, path to rendered diagram)
        output_path: Where to write the doc
        since: Only include entries since this date (ISO format)

    Returns:
        Path to the generated file
    """
    # Filter by date if requested
    if since:
        entries = [e for e in entries if e.get("timestamp", "") >= since]

    # Reverse chronological
    entries = sorted(entries, key=lambda e: e.get("timestamp", ""), reverse=True)

    lines = [
        "# 🏗️ Living Architecture Document",
        "",
        f"*Generated by DesignScribe — {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}*",
        "",
        "---",
        "",
    ]

    if not entries:
        lines.append("*No recorded changes yet.*")
    else:
        for entry in entries:
            ts = entry.get("timestamp", "unknown")
            task = entry.get("task", "")
            summary = entry.get("summary", "No summary")
            rationale = entry.get("rationale", "")
            data_flow = entry.get("data_flow", "")
            impact = entry.get("impact", [])
            diagram = entry.get("diagram", "")
            diagram_path = entry.get("diagram_path", "")
            changes = entry.get("changes", [])

            # Header
            lines.append(f"## 📝 {ts}")
            if task:
                lines.append(f"**Task:** {task}")
            lines.append("")

            # Summary
            lines.append(f"### Summary")
            lines.append(summary)
            lines.append("")

            # Rationale
            if rationale:
                lines.append(f"### Rationale")
                lines.append(rationale)
                lines.append("")

            # Data flow
            if data_flow:
                lines.append(f"### Data Flow")
                lines.append(data_flow)
                lines.append("")

            # Changed files
            if changes:
                files = list(set(c.get("file", "") for c in changes if c.get("file")))
                if files:
                    lines.append("### Changed Files")
                    for f in sorted(files):
                        lines.append(f"- `{f}`")
                    lines.append("")

            # Impact
            if impact:
                lines.append("### Impact")
                for f in impact:
                    lines.append(f"- `{f}`")
                lines.append("")

            # Diagram
            if diagram:
                lines.append("### Architecture Diagram")
                if diagram_path:
                    # Embed image
                    lines.append(f"![diagram]({diagram_path})")
                    lines.append("")
                    lines.append("<details><summary>Mermaid source</summary>")
                    lines.append("")
                    lines.append("```mermaid")
                    lines.append(diagram)
                    lines.append("```")
                    lines.append("</details>")
                else:
                    lines.append("```mermaid")
                    lines.append(diagram)
                    lines.append("```")
                lines.append("")

            lines.append("---")
            lines.append("")

    content = "\n".join(lines)
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    Path(output_path).write_text(content, encoding="utf-8")
    return output_path


def append_entry(entry: dict, output_path: str = "living-arch.md") -> str:
    """Append a single entry to the existing living architecture doc.

    If the file doesn't exist, creates it. Otherwise, inserts the new entry
    at the top (after the header) to maintain reverse-chronological order.
    """
    p = Path(output_path)

    if not p.exists():
        return render_markdown([entry], output_path)

    # Read existing content
    existing = p.read_text(encoding="utf-8")

    # Build the new entry markdown
    ts = entry.get("timestamp", "unknown")
    task = entry.get("task", "")
    summary = entry.get("summary", "No summary")
    rationale = entry.get("rationale", "")
    data_flow = entry.get("data_flow", "")
    impact = entry.get("impact", [])
    diagram = entry.get("diagram", "")
    diagram_path = entry.get("diagram_path", "")
    changes = entry.get("changes", [])

    entry_lines = [f"## 📝 {ts}"]
    if task:
        entry_lines.append(f"**Task:** {task}")
    entry_lines.append("")
    entry_lines.append(f"### Summary")
    entry_lines.append(summary)
    entry_lines.append("")
    if rationale:
        entry_lines.append(f"### Rationale")
        entry_lines.append(rationale)
        entry_lines.append("")
    if data_flow:
        entry_lines.append(f"### Data Flow")
        entry_lines.append(data_flow)
        entry_lines.append("")
    if changes:
        files = list(set(c.get("file", "") for c in changes if c.get("file")))
        if files:
            entry_lines.append("### Changed Files")
            for f in sorted(files):
                entry_lines.append(f"- `{f}`")
            entry_lines.append("")
    if impact:
        entry_lines.append("### Impact")
        for f in impact:
            entry_lines.append(f"- `{f}`")
        entry_lines.append("")
    if diagram:
        entry_lines.append("### Architecture Diagram")
        if diagram_path:
            entry_lines.append(f"![diagram]({diagram_path})")
            entry_lines.append("")
            entry_lines.append("<details><summary>Mermaid source</summary>")
            entry_lines.append("")
            entry_lines.append("```mermaid")
            entry_lines.append(diagram)
            entry_lines.append("```")
            entry_lines.append("</details>")
        else:
            entry_lines.append("```mermaid")
            entry_lines.append(diagram)
            entry_lines.append("```")
        entry_lines.append("")
    entry_lines.append("---")
    entry_lines.append("")

    new_entry = "\n".join(entry_lines)

    # Find insertion point (after the header block, before first entry)
    marker = "---\n"
    idx = existing.find(marker)
    if idx != -1:
        insert_after = idx + len(marker)
        # Skip any blank lines after the marker
        while insert_after < len(existing) and existing[insert_after] == "\n":
            insert_after += 1
        updated = existing[:insert_after] + "\n" + new_entry + existing[insert_after:]
    else:
        # No header — just prepend
        updated = new_entry + "\n" + existing

    p.write_text(updated, encoding="utf-8")
    return output_path
